"""
GoMufi — Gemini Yapay Zeka (AI) İçerik Üretim Router'ı.
"""
import json
import os
import random
import copy
import io
from typing import List, Optional, Any, Dict
from fastapi import APIRouter, Depends, HTTPException, Form, File, UploadFile, BackgroundTasks
from pydantic import BaseModel
from google import genai
from google.genai import types
from core.config import settings
from auth.dependencies import get_current_teacher_id, get_current_user_info
from connect_db import get_db, AsyncSession, SessionLocal
from sqlalchemy.future import select
from sqlalchemy import delete
from models.ai_usage_log import AIUsageLog
from models.course import Course

import urllib.parse
import urllib.request
import re

async def record_ai_usage(
    db: AsyncSession,
    teacher_id: Optional[int],
    action: str,
    model_name: str,
    response: Any,
    details: Optional[str] = None,
    course_id: Optional[int] = None,
    course_title: Optional[str] = None
):
    """Helper function to extract usage metadata from Gemini response and store log in database."""
    try:
        usage = getattr(response, "usage_metadata", None)
        prompt_tokens = getattr(usage, "prompt_token_count", 0) or 0
        candidates_tokens = getattr(usage, "candidates_token_count", 0) or 0
        total_tokens = getattr(usage, "total_token_count", 0) or (prompt_tokens + candidates_tokens)
        
        # Pricing per 1,000,000 tokens (Google AI Studio Official Rates for Gemini 2.5 Flash)
        rate_input = 0.30 / 1_000_000
        rate_output = 2.50 / 1_000_000
        cost_usd = (prompt_tokens * rate_input) + (candidates_tokens * rate_output)
        
        log_entry = AIUsageLog(
            teacher_id=teacher_id,
            course_id=course_id,
            course_title=course_title,
            action=action,
            model_name=model_name,
            prompt_tokens=prompt_tokens,
            candidates_tokens=candidates_tokens,
            total_tokens=total_tokens,
            cost_usd=round(cost_usd, 6),
            details=details
        )
        db.add(log_entry)
        await db.commit()
    except Exception as err:
        print(f"Warning: Failed to record AI usage log: {err}")


def format_templates_summary(cat_list: List[Dict[str, Any]]) -> str:
    """Format templates list into compact single-line descriptions to minimize prompt tokens."""
    lines = []
    for t in cat_list:
        els = []
        for el in t.get("elements", []):
            m_char = f", maxChars:{el['maxChars']}" if el.get("maxChars") else ""
            els.append(f"{el['id']} ({el['type']}{m_char})")
        lines.append(f"- Template ID: \"{t['id']}\" | Title: \"{t['title']}\" | Elements: [{', '.join(els)}]")
    return "\n".join(lines)


def get_web_image(query: str, is_fallback: bool = False) -> str:
    # Basic translation dictionary for common academic/structural fallback terms
    translation_dict = {
        "giris": "introduction",
        "nedir": "about",
        "kurulum": "setup",
        "ortami": "workspace",
        "tarih": "history",
        "cografya": "geography",
        "matematik": "mathematics",
        "fizik": "physics",
        "kimya": "chemistry",
        "biyoloji": "biology",
        "operatorler": "operators",
        "degiskenler": "variables",
    }
    
    tr_map = str.maketrans("çğıöşüÇĞİÖŞÜ", "cgiosuCGIOSU")
    query_clean = query.translate(tr_map).lower()
    
    # Split query into words
    words = [w.strip() for w in re.split(r'[^a-zA-Z0-9]', query_clean) if w.strip()]
    
    eng_keywords = []
    for w in words:
        if w in translation_dict:
            eng_keywords.append(translation_dict[w])
        elif not is_fallback and w.isalnum():
            # If not fallback, it is English keywords generated by Gemini, so keep it!
            eng_keywords.append(w)
            
    if not eng_keywords:
        eng_keywords = ["education"]
        
    # Get unique keywords preserving order
    unique_keywords = list(dict.fromkeys(eng_keywords))
    keywords_str = ",".join(unique_keywords)
    return f"https://loremflickr.com/640/480/{urllib.parse.quote(keywords_str)}"

router = APIRouter()


class CustomLessonInput(BaseModel):
    title: str
    topics: List[str]


class GenerateRoadmapRequest(BaseModel):
    topic: str
    difficulty: str
    lessons_count: int
    audience: str
    pdf_content: Optional[str] = None
    custom_lessons: Optional[List[CustomLessonInput]] = None


class GenerateLessonSlidesRequest(BaseModel):
    topic: str
    difficulty: str
    audience: str
    lesson_number: int
    lesson_title: str
    lesson_objective: str
    modules: List[Any]
    pdf_content: Optional[str] = None


# --- GEMINI STRUCTURED OUTPUT SCHEMAS ---

class RoadmapModuleStructure(BaseModel):
    type: str  # e.g. "UNDERSTAND", "APPLY", "CONNECT", "CREATE", "QUIZ", "HOMEWORK"
    topic: str  # Specific sub-topic or task title

class RoadmapLessonStructure(BaseModel):
    lessonNumber: int
    title: str
    objective: str
    modules: List[RoadmapModuleStructure]

class RoadmapStructureResponse(BaseModel):
    courseTitle: str
    lessons: List[RoadmapLessonStructure]


class SuggestLessonModulesRequest(BaseModel):
    lesson_title: str
    course_topic: str
    difficulty: str
    audience: str
    pdf_content: Optional[str] = None


class SuggestLessonModulesResponse(BaseModel):
    objective: str
    modules: List[RoadmapModuleStructure]


class SuggestLessonTitleRequest(BaseModel):
    course_topic: str
    difficulty: str
    audience: str
    lesson_number: int
    existing_lessons: List[str]
    pdf_content: Optional[str] = None


class SuggestLessonTitleResponse(BaseModel):
    titles: List[str]


class SuggestLevelDetailsRequest(BaseModel):
    course_topic: str
    difficulty: str
    audience: str
    lesson_title: str
    module_type: str
    sibling_modules: List[Dict[str, str]]
    pdf_content: Optional[str] = None


class SuggestLevelDetailsResponse(BaseModel):
    title: str
    topic: str


class SuggestedLessonPlanItem(BaseModel):
    lesson_number: int
    title: str
    topics: List[str]


class SuggestCurriculumParametersResponse(BaseModel):
    suggested_lessons: List[SuggestedLessonPlanItem]
    suggested_lessons_count: int


class SuggestRawTopicsResponse(BaseModel):
    suggested_topics: List[str]


class DistributeTopicsRequest(BaseModel):
    topics: List[str]
    lesson_duration: int
    lessons_count: int


class ExpandTopicsRequest(BaseModel):
    topics: List[str]
    course_topic: str
    difficulty: str
    audience: str
    target_count: Optional[int] = None


class ExpandTopicsResponse(BaseModel):
    expanded_topics: List[str]


class ElementContentPair(BaseModel):
    elementId: str
    content: str


class AILevelSlide(BaseModel):
    selectedTemplateId: str
    elementContents: List[ElementContentPair]

class AILevelContent(BaseModel):
    lessonNumber: int
    moduleIndex: int
    slides: List[AILevelSlide]

class AILevelContentsResponse(BaseModel):
    levelContents: List[AILevelContent]


class QuizOption(BaseModel):
    text: str
    isCorrect: bool

class QuizQuestion(BaseModel):
    questionText: str
    options: List[QuizOption]

class HomeworkData(BaseModel):
    title: str
    instructions: str
    submissionType: str
    points: int
    starterCode: str

class LessonSlidesResponse(BaseModel):
    modules_content: List[AILevelContent]
    quiz_map: List[QuizQuestion]
    homework_map: HomeworkData


@router.post("/courses/generate_roadmap")
async def generate_roadmap_api(
    req: GenerateRoadmapRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    TEMPLATES_PATH = "slide_templates.json"
    try:
        # Load templates
        templates = []
        if os.path.exists(TEMPLATES_PATH):
            with open(TEMPLATES_PATH, "r", encoding="utf-8") as f:
                templates = json.load(f)
                
        # Group templates by category
        templates_by_category = {
            "ANLA": [],
            "UYGULA": [],
            "BİRLEŞTİR": [],
            "ÜRET": []
        }
        for t in templates:
            cat = t.get("category", "").upper()
            if cat in templates_by_category:
                elements_info = []
                for el in t.get("elements", []):
                    if el.get("type") in ["text", "code", "sticky", "challenge", "code_editor", "connection_task", "production_task", "image"]:
                        elements_info.append({
                            "id": el.get("id"),
                            "type": el.get("type"),
                            "placeholder": el.get("content"),
                            "maxChars": el.get("maxChars")
                        })
                templates_by_category[cat].append({
                    "id": t.get("id"),
                    "title": t.get("title"),
                    "description": t.get("description"),
                    "elements": elements_info
                })
                
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        # --- PHASE 1: GENERATE ROADMAP STRUCTURE ---
        prompt_step1 = f"""
Role: You are an expert instructional designer and curriculum planner. Türkçe cevap ver.
Your task is only to design the structure of a learning roadmap (lessons and modules sequence).

Goal: Given the course topic, difficulty, desired lesson count, and target audience, generate the sequence of lessons and modules.

Requirements:
- The roadmap consists of lessons.
- Each lesson contains a list of modules representing levels.
- Modules are selected from: UNDERSTAND, APPLY, CONNECT, CREATE, QUIZ, HOMEWORK.
- **FLEXIBLE PEDAGOGICAL FLOW & MODULE RULES**:
  - A lesson can cover 1 or MULTIPLE sub-topics.
  - For EACH distinct sub-topic taught in the lesson, generate a pair of `UNDERSTAND` (Anla - Konu Teorisi) followed immediately by `APPLY` (Uygula - Kodlama Pratiği).
  - Therefore, a lesson CAN contain MULTIPLE `UNDERSTAND` and `APPLY` pairs if there are multiple sub-topics in that lesson (e.g., `UNDERSTAND(Konu 1) -> APPLY(Konu 1) -> UNDERSTAND(Konu 2) -> APPLY(Konu 2)...`). Do NOT limit a lesson to only one pair if multiple concepts are taught!
  - After all sub-topic theory & practice pairs in the lesson, you MUST include:
    1. At least one `CONNECT` module (Birleştir - Öğrenilen Kavramları Birleştirme Görevi / Bulmaca)
    2. At least one `CREATE` module (Üret - Mini Proje / Üretim Görevi)
    3. Exactly one `QUIZ` or `HOMEWORK` module (Değerlendirme Testi veya Ödev)
  - Summary of lesson module sequence: `[(UNDERSTAND -> APPLY)* (1 or more pairs)] -> CONNECT -> CREATE -> QUIZ (or HOMEWORK)`.
- **CRITICAL TITLE LENGTH CONSTRAINT (STRICT RULE)**: Every lesson title (`title`) and module topic string (`topic`) MUST be concise and MUST NOT exceed 30 characters in total length (e.g., 'Python Kurulumu', 'Değişken Tanımlama', 'Koşullu İfadeler'). Never generate verbose or long titles exceeding 30 characters.
- Each module in the lessons modules list MUST have a specific, distinct `"topic"` string explaining what specific sub-topic or task this module covers. This is critical for generating unique slide contents later.
- Return ONLY valid JSON matching the structure below. No markdown formatting, no text before or after the JSON.

Expected JSON Structure:
{{
  "courseTitle": "...",
  "lessons": [
    {{
      "lessonNumber": 1,
      "title": "Lesson title (Türkçe)",
      "objective": "Lesson learning objective (Türkçe)",
      "modules": [
        {{ "type": "UNDERSTAND", "topic": "1. Konu Anlatımı Başlığı (Türkçe)" }},
        {{ "type": "APPLY", "topic": "1. Konu Kodlama Pratiği Görevi (Türkçe)" }},
        {{ "type": "UNDERSTAND", "topic": "2. Konu Anlatımı Başlığı (Varsa) (Türkçe)" }},
        {{ "type": "APPLY", "topic": "2. Konu Kodlama Pratiği Görevi (Varsa) (Türkçe)" }},
        {{ "type": "CONNECT", "topic": "Öğrenilen Tüm Kavramları Birleştirme Görevi (Türkçe)" }},
        {{ "type": "CREATE", "topic": "Mini Proje Üretim Görevi (Türkçe)" }},
        {{ "type": "QUIZ", "topic": "Ders Değerlendirme Testi (Türkçe)" }}
      ]
    }}
  ]
}}

Input:
Topic: {req.topic}
Difficulty: {req.difficulty}
Lessons Count: {req.lessons_count}
Audience: {req.audience}
"""
        response_step1 = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt_step1,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=RoadmapStructureResponse
            )
        )
        await record_ai_usage(db, teacher_id, "generate_roadmap_structure", "gemini-2.5-flash", response_step1)
        
        roadmap_structure = json.loads(response_step1.text.strip())
        
        # --- PHASE 2: GENERATE SLIDES CONTENT FOR ALL MODULES ---
        prompt_step2 = f"""
Role: You are an expert instructional designer and curriculum planner. Türkçe cevap ver.
Your task is to write detailed educational slide contents for the UNDERSTAND, APPLY, CONNECT, and CREATE modules in the provided curriculum.

Course:
Topic: {req.topic}
Difficulty: {req.difficulty}
Audience: {req.audience}

Curriculum Structure to populate:
{json.dumps(roadmap_structure, ensure_ascii=False, indent=2)}

Available Templates for each category:
- UNDERSTAND (ANLA) templates:
{format_templates_summary(templates_by_category["ANLA"])}

- APPLY (UYGULA) templates:
{format_templates_summary(templates_by_category["UYGULA"])}

- CONNECT (BİRLEŞTİR) templates:
{format_templates_summary(templates_by_category["BİRLEŞTİR"])}

- CREATE (ÜRET) templates:
{format_templates_summary(templates_by_category["ÜRET"])}

Requirements:
- For each module in the curriculum of type UNDERSTAND, APPLY, CONNECT, and CREATE, you MUST generate slide contents.
- For each module, choose the most suitable template from the available templates of its category.
- UNIVERSAL PEDAGOGICAL RULE FOR ALL TOPICS (STRICT CONSTRAINT):
  * For UNDERSTAND (ANLA): Generate 2 to 4 slides explaining the lesson concepts. Crucially, EVERY single concept, formula, syntax, method, command, tool, function, or technique that will be required or practiced in the subsequent APPLY module MUST be explicitly taught, explained, and demonstrated with a concrete example (code block, text example, or formula breakdown) in these UNDERSTAND slides. Never explain theory without showing a concrete working example.
  * For APPLY (UYGULA): Generate 1 to 2 slides with task instructions or challenges. The student MUST ONLY be asked to apply or solve what was explicitly demonstrated and taught in the immediately preceding UNDERSTAND slides. It is STRICTLY FORBIDDEN to introduce or ask for any new concept, syntax, method, function, or formula in APPLY that was not explicitly shown in UNDERSTAND.
- For CONNECT (BİRLEŞTİR): This module MUST NOT teach new theory, MUST NOT use daily life analogies, and MUST NOT provide concept definitions. Its ONLY goal is to make the student combine and use two or more previously learned concepts together in a single coding challenge. 
  * In the Connection Task template, the `connection_task` element content MUST be a JSON-serialized string formatted exactly like this to populate the connection task widget:
    {{"previousTopic": "Name of previous topic (e.g. Değişken Tanımlama)", "currentTopic": "Name of current topic (e.g. Koşullu İfadeler)", "taskText": "Detailed connection coding challenge instructions asking the student to combine both topics."}}
- For CREATE (ÜRET): This module is for building a small mini-project.
  * In the Produce Task template, the `production_task` element content MUST be a JSON-serialized string formatted exactly like this to populate the production task widget:
    {{"projectTitle": "Title of the project (e.g. Hesap Makinesi)", "taskText": "Detailed instructions on what to build", "expectedOutput": "Example console output showing what the running code should display", "estimatedTime": "Estimated completion time (e.g. 15 Dakika)", "hints": "Useful coding hint or tip"}}
  * Note: The JSON string for `connection_task` or `production_task` must be escaped properly so that it is a valid JSON string inside the outer JSON response. Escape double quotes with `\"` and use `\n` for line breaks. Do not write raw newlines inside the string values.
- CRITICAL IMAGE REQUIREMENT: Your templates contain "image" elements. For EVERY "image" element, you MUST populate the "content" field in "elementContents" with a descriptive English search query (3-5 words) representing the visual content for that specific slide (e.g., "ancient roman soldier armor" for a history slide, "python coding mathematical operator" for a programming slide, "cell division biology microscope" for a biology slide). DO NOT leave "image" elements empty or unpopulated.
- For each element you populate in `elementContents`, you MUST strictly respect the `maxChars` limit defined in the template. The number of characters of your generated text (including spaces) for that element ID MUST NOT exceed its `maxChars` value to prevent UI text overflow. This is a critical visual layout constraint.
- Populate `elementContents` mapping the template element IDs to your generated educational contents in Turkish.
- Return ONLY valid JSON matching the structure below. No markdown formatting, no text before or after the JSON.

Expected JSON Structure:
{{
  "levelContents": [
    {{
      "lessonNumber": 1,
      "moduleIndex": 0, // 0-based index of the module inside the lesson's modules list
      "slides": [
        {{
          "selectedTemplateId": "template_id_here",
          "elementContents": [
             {{ "elementId": "element_id_1", "content": "Generated text explanation in Turkish" }},
             {{ "elementId": "element_id_2", "content": "Generated python code or note in Turkish..." }}
          ]
        }}
      ]
    }}
  ]
}}
"""
        response_step2 = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt_step2,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=AILevelContentsResponse
            )
        )
        await record_ai_usage(db, teacher_id, "generate_roadmap_content", "gemini-2.5-flash", response_step2)
        
        slide_contents_data = json.loads(response_step2.text.strip())
        level_contents_list = slide_contents_data.get("levelContents", [])
        
        # --- PHASE 3: MAP AND CONSTRUCT THE VISUAL CURRICULUM AND NOTES ---
        generated_lessons = roadmap_structure.get("lessons", [])
        
        curriculum = []
        notes = []
        overall_idx = 1
        
        theme_map = {
          "UNDERSTAND": "purple",
          "APPLY": "cyan",
          "CONNECT": "green",
          "CREATE": "yellow",
          "QUIZ": "quiz",
          "HOMEWORK": "homework"
        }
        
        all_templates_map = {
            "UNDERSTAND": templates_by_category["ANLA"],
            "APPLY": templates_by_category["UYGULA"],
            "CONNECT": templates_by_category["BİRLEŞTİR"],
            "CREATE": templates_by_category["ÜRET"]
        }
        
        for l_idx, les in enumerate(generated_lessons):
            lesson_num = les.get("lessonNumber") or (l_idx + 1)
            modules = les.get("modules", [])
            for m_idx, mod in enumerate(modules):
                mod_type = mod.get("type", "UNDERSTAND").upper()
                mapped_theme = theme_map.get(mod_type, "purple")
                
                level_id = f"sec_ai_{int(random.random() * 1000000000)}"
                
                raw_topic = (mod.get("topic") or "").strip()
                clean_topic = re.sub(r"^(?:Ders\s+\d+[:\s\-]*|\d+[\.\)\s\-]*)", "", raw_topic, flags=re.IGNORECASE).strip()
                if not clean_topic:
                    clean_topic = (les.get("title") or "Ders Konusu").strip()
                    clean_topic = re.sub(r"^(?:Ders\s+\d+[:\s\-]*|\d+[\.\)\s\-]*)", "", clean_topic, flags=re.IGNORECASE).strip()
                
                final_node_title = clean_topic[:30] if mod_type not in ["QUIZ", "HOMEWORK"] else ("Konu Testi" if mod_type == "QUIZ" else "Ödev Görevi")
                
                node = {
                  "id": level_id,
                  "title": final_node_title,
                  "theme": mapped_theme,
                  "lectures": []
                }
                
                if m_idx == 0:
                  node["lessonTopic"] = les.get("title") or f"Ders Konusu {lesson_num}"
                  node["lessonNumber"] = lesson_num
                  
                curriculum.append(node)
                overall_idx += 1
                
                # Check if we should build slide content for this module type
                if mod_type in ["UNDERSTAND", "APPLY", "CONNECT", "CREATE"]:
                    # Find matching generated slide contents
                    matched_content = next((
                        lc for lc in level_contents_list 
                        if str(lc.get("lessonNumber")) == str(lesson_num) and str(lc.get("moduleIndex")) == str(m_idx)
                    ), None)
                    if not matched_content:
                        matched_content = next((
                            lc for lc in level_contents_list 
                            if str(lc.get("lessonNumber")) == str(lesson_num) and lc.get("moduleType", "").upper() == mod_type
                        ), None)
                    
                    
                    cat_templates = all_templates_map.get(mod_type, [])
                    
                    slides_to_add = []
                    ai_slides = []
                    if matched_content:
                        ai_slides = matched_content.get("slides") or []
                    
                    # Fallback if empty but templates exist (create at least 1 placeholder slide)
                    if not ai_slides and cat_templates:
                        ai_slides = [{"selectedTemplateId": cat_templates[0]["id"], "elementContents": {}}]
                        
                    if isinstance(ai_slides, dict):
                        ai_slides = [ai_slides]
                    elif not isinstance(ai_slides, list):
                        ai_slides = []
                        
                    for ai_slide in ai_slides:
                        sel_template_id = ai_slide.get("selectedTemplateId")
                        raw_contents = ai_slide.get("elementContents") or []
                        elem_contents = {}
                        if isinstance(raw_contents, list):
                            for pair in raw_contents:
                                if isinstance(pair, dict) and "elementId" in pair:
                                    elem_contents[pair["elementId"]] = pair.get("content") or ""
                        elif isinstance(raw_contents, dict):
                            elem_contents = raw_contents
                        
                        # Find original template elements
                        selected_t = next((t for t in templates if t.get("id") == sel_template_id), None)
                        # Fallback to category template if not found
                        if not selected_t and cat_templates:
                            selected_t = next((t for t in templates if t.get("id") == cat_templates[0]["id"]), None)
                            
                        if selected_t:
                            copied_elements = []
                            for el in selected_t.get("elements", []):
                                 el_copy = copy.deepcopy(el)
                                 el_id = el_copy.get("id")
                                 el_type = el_copy.get("type")
                                 
                                 # Pre-evaluate value if present
                                 val = elem_contents.get(el_id) if el_id in elem_contents else ""
                                 
                                 if el_type == "image":
                                     # Determine query - fallback to module topic or lesson title if empty
                                     query = val if val else (mod.get("topic") or les.get("title") or "coding")
                                     is_fb = not bool(val)
                                     img_url = get_web_image(query, is_fallback=is_fb)
                                     el_copy["content"] = img_url
                                     el_copy["imageUrl"] = img_url
                                     el_copy["src"] = img_url
                                 elif el_id in elem_contents:
                                     if el_type == "connection_task":
                                         import json as pyjson
                                         try:
                                             parsed = pyjson.loads(val)
                                             el_copy["content"] = parsed.get("taskText") or val
                                             if "extra" not in el_copy or not el_copy["extra"]:
                                                 el_copy["extra"] = {}
                                             el_copy["extra"]["previousTopic"] = parsed.get("previousTopic") or "Önceki Konu"
                                             el_copy["extra"]["currentTopic"] = parsed.get("currentTopic") or "Şimdiki Konu"
                                         except Exception:
                                             el_copy["content"] = val
                                     elif el_type == "production_task":
                                         import json as pyjson
                                         try:
                                             parsed = pyjson.loads(val)
                                             el_copy["content"] = parsed.get("taskText") or val
                                             if "extra" not in el_copy or not el_copy["extra"]:
                                                 el_copy["extra"] = {}
                                             el_copy["extra"]["projectTitle"] = parsed.get("projectTitle") or "Proje Başlığı"
                                             el_copy["extra"]["expectedOutput"] = parsed.get("expectedOutput") or ""
                                             el_copy["extra"]["estimatedTime"] = parsed.get("estimatedTime") or "10 Dakika"
                                             el_copy["extra"]["hints"] = parsed.get("hints") or ""
                                         except Exception:
                                             el_copy["content"] = val
                                     else:
                                         el_copy["content"] = val
                                 
                                 copied_elements.append(el_copy)
                                
                            slide = {
                                "id": int(random.random() * 1000000000),
                                "elements": copied_elements,
                                "background": selected_t.get("background", "default")
                            }
                            slides_to_add.append(slide)
                            
                    if slides_to_add:
                        note = {
                            "id": level_id,
                            "noteTitle": node["title"],
                            "slides": slides_to_add
                        }
                        notes.append(note)
                        
        return {"success": True, "curriculum": curriculum, "notes": notes, "roadmap": roadmap_structure}
        
    except Exception as e:
        print(f"Error generating roadmap: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/suggest_raw_topics")
async def suggest_raw_topics_api(
    topic: str = Form(...),
    difficulty: str = Form(...),
    audience: str = Form(...),
    pdf_file: Optional[UploadFile] = File(None),
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    try:
        pdf_text = ""
        if pdf_file:
            pdf_bytes = await pdf_file.read()
            try:
                from pypdf import PdfReader
                reader = PdfReader(io.BytesIO(pdf_bytes))
                for page in reader.pages:
                    text = page.extract_text()
                    if text:
                        pdf_text += text + "\n"
            except Exception as e:
                print(f"Error parsing PDF: {e}")
                raise HTTPException(status_code=400, detail=f"PDF dosyası okunurken bir hata oluştu: {str(e)}")

        client = genai.Client(api_key=settings.MY_API_KEY)
        
        pdf_context = ""
        if pdf_text:
            pdf_context = f"\n\nSource Material (PDF Content):\n{pdf_text[:40000]}\n\nInstruction: Base your curriculum topic suggestions strictly on the provided Source Material PDF above."

        prompt = f"""
Role: You are an expert computer science curriculum architect and educational planner. Türkçe cevap ver.
Your task is to analyze the course topic, difficulty, audience, and optional PDF content, and suggest:
- A flat sequence of substantive, practical coding topics (subject headings) that must be covered in this course (typically between 5 and 15 topics).
- **Strictly Ban Trivial/Fluff Headings**: Do not generate separate topics for history (e.g., Python history, versions 2.x vs 3.x), compiler/interpreter definitions, syntax trivia (like comment `#` character), or individual data types (like string, integer, float as separate topics).
- **Cluster Into Substantive Headings**: Group minor details and syntax trivia together into comprehensive, high-density practical headers (each representing a significant coding outcome and at least 20-30 minutes of real teaching time).
  - *Incorrect (Do NOT suggest)*: ["Python Tarihçesi", "Python Kurulumu", "print() kullanımı", "Yorum satırları"]
  - *Correct (Instead suggest)*: ["Python Kurulumu, İlk Programı Çalıştırma (print, yorumlar)"]
  - *Incorrect (Do NOT suggest)*: ["Değişken Nedir", "string veri tipi", "integer veri tipi", "float veri tipi", "tip dönüşümleri"]
  - *Correct (Instead suggest)*: ["Değişkenler, Temel Veri Tipleri (str, int, float, bool) ve Tip Dönüşümleri (casting)"]
  - *Incorrect (Do NOT suggest)*: ["Aritmetik Operatörler", "String Birleştirme", "len() metodu"]
  - *Correct (Instead suggest)*: ["Temel Aritmetik ve String Operatörleri (len(), birleştirme)"]

{pdf_context}

Course Parameters:
Course Topic: {topic}
Difficulty: {difficulty}
Target Audience: {audience}

Return ONLY valid JSON matching the structure below. No markdown formatting.

Expected JSON Structure:
{{
  "suggested_topics": [
    "Python Kurulumu, İlk Programı Çalıştırma (print, yorumlar)",
    "Değişkenler, Temel Veri Tipleri (str, int, float, bool) ve Tip Dönüşümleri (casting)",
    "Temel Aritmetik ve String Operatörleri (len(), birleştirme)"
  ]
}}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=SuggestRawTopicsResponse
            )
        )
        await record_ai_usage(db, teacher_id, "suggest_raw_topics", "gemini-2.5-flash", response)
        data = json.loads(response.text.strip())
        return {
            "success": True, 
            "suggested_topics": data.get("suggested_topics", []), 
            "pdf_text": pdf_text
        }
    except Exception as e:
        print(f"Error suggesting raw topics: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/distribute_topics_into_lessons")
async def distribute_topics_into_lessons_api(
    req: DistributeTopicsRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    try:
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        prompt = f"""
Role: You are an expert computer science curriculum architect and instructional designer. Türkçe cevap ver.
Your task is to take a flat list of course sub-topics, the duration of each lesson in minutes, and the target lesson count, and distribute these topics logically across lessons.

Input Parameters:
Topics to distribute: {req.topics}
Lesson Duration: {req.lesson_duration} minutes per lesson.
Target Lessons Count: {req.lessons_count if req.lessons_count > 0 else 'AI to determine optimal count based on duration and topic list (typically between 3 and 12).'}

Critical Pedagogical & Weight-Balancing Requirements:
1. **Analyze Topic Complexity/Weight**: 
   - Simple introductory sub-topics (e.g., printing, comments, variables, simple data types, type conversion) should be grouped together logically.
   - Substantive/complex topics (e.g., loops, functions, OOP, databases, external libraries like `pygame`, web frameworks like `flask`) are heavy and require dedicated lessons.
2. **Teachable Content Ceiling & Full Utilization (Crucial)**:
   - Ensure each lesson is fully and realistically utilized according to the requested duration. A 60-minute lesson should cover a rich set of topics, ideally **2 to 3 substantive topic headings** (or 3 to 5 if they are smaller).
   - Do NOT leave a lesson with only a single simple/minor topic heading (like only "installation and print") if there are other basic topics that can logically be combined into it (like "variables and data types"). Group them together.
   - However, do NOT assign more than 3 to 5 topic headings to a single lesson (6 or more is unteachable in 60 minutes).
   - If the user requested a target lesson count that is larger than the number of clustered lessons, do NOT create placeholder "review/lab/project/recap" lessons (e.g. do not suggest generic review topics like "Önceki Derslerin Gözden Geçirilmesi"). Instead, split the input topics into finer-grained, more detailed sub-topics and distribute them evenly across the requested lessons so that each lesson has unique, progressive content.
3. **Prevent Cramming of Advanced Concepts**:
   - Under no circumstances should massive distinct frameworks (like `pygame` and `flask`) be combined in a single lesson, especially not alongside control flows (like loops).
   - If the list includes advanced frameworks/libraries, give them their own dedicated lessons.
4. **No Information Loss**: All input topics must be mapped to at least one lesson. Do not skip or omit any of them.
5. **Lesson Titles**: Provide a concise title for each lesson reflecting its consolidated focus (e.g., "Ders 1: Giriş, print() ve Temel Veri Tipleri", "Ders 2: Kontrol Yapıları ve Döngüler", etc.).
6. Return ONLY valid JSON matching the structure below. No markdown formatting.

Expected JSON Structure:
{{
  "suggested_lessons": [
    {{
      "lesson_number": 1,
      "title": "Suggested Lesson 1 Title",
      "topics": [
        "Topic A",
        "Topic B"
      ]
    }}
  ],
  "suggested_lessons_count": 1
}}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=SuggestCurriculumParametersResponse
            )
        )
        await record_ai_usage(db, teacher_id, "distribute_topics", "gemini-2.5-flash", response)
        data = json.loads(response.text.strip())
        return {
            "success": True, 
            "suggested_lessons": data.get("suggested_lessons", []), 
            "suggested_lessons_count": data.get("suggested_lessons_count", 6)
        }
    except Exception as e:
        print(f"Error distributing topics: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/expand_topics")
async def expand_topics_api(
    req: ExpandTopicsRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    try:
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        target_count_val = req.target_count if req.target_count and req.target_count > 0 else None
        count_instruction = ""
        if target_count_val:
            count_instruction = f"\nRequirement: You MUST generate exactly {target_count_val} total sub-topic strings in the final 'expanded_topics' array."
        else:
            count_instruction = "\nRequirement: Suggest around 3 to 5 sub-topics per high-level topic."
            
        prompt = f"""
Role: You are an expert computer science curriculum architect and educational planner. Türkçe cevap ver.
Your task is to take a list of course topic headings, analyze them in the context of the course '{req.course_topic}', and expand them into a more detailed, high-density sequence of practical sub-topics.
Specifically:
1. Identify high-level, short, or broad topic headings (for example, "Flask", "OOP", "Database", "Python Giriş", "CSS").
2. Subdivide these high-level headings into separate, detailed, progressive sub-topics. For example:
   - "Flask" should be expanded into sub-topics like: "Flask Kurulumu ve İlk Uygulama", "Flask Yönlendirme (Routing) ve Dinamik URL'ler", "Jinja2 Şablon Yapısı (Templates)", "Flask Form Yönetimi ve POST/GET İstekleri", "Flask ile Veritabanı Entegrasyonu (SQLAlchemy)".
   - "Python Giriş" should be expanded into: "Python Kurulumu ve Temel print/yorumlar", "Değişken Tanımlama ve Temel Veri Tipleri", "Tip Dönüşümleri (Casting)".
3. If a topic is already highly specific and detailed, keep it as is.
4. Do NOT output generic review, recap, or exam topics.
5. Preserve the overall logical learning sequence.
{count_instruction}

Input Parameters:
Course Topic Context: {req.course_topic}
Difficulty Level: {req.difficulty}
Target Audience: {req.audience}
Current Topics to Expand: {req.topics}

Return ONLY valid JSON matching the structure below. No markdown formatting.

Expected JSON Structure:
{{
  "expanded_topics": [
    "Expanded topic 1",
    "Expanded topic 2",
    "..."
  ]
}}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=ExpandTopicsResponse
            )
        )
        await record_ai_usage(db, teacher_id, "expand_topics", "gemini-2.5-flash", response, details=f"Kurs: '{req.course_topic}' | Konu Genişletme")
        data = json.loads(response.text.strip())
        return {
            "success": True, 
            "expanded_topics": data.get("expanded_topics", [])
        }
    except Exception as e:
        print(f"Error expanding topics: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/generate_roadmap_structure")
async def generate_roadmap_structure_api(
    req: GenerateRoadmapRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    try:
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        pdf_context = ""
        if req.pdf_content:
            pdf_context = f"\n\nSource Material (PDF Content):\n{req.pdf_content[:40000]}\n\nInstruction: Base the curriculum topics, order, and explanations strictly on the provided Source Material PDF above."

        custom_lessons_instruction = ""
        if req.custom_lessons:
            custom_lessons_instruction = f"\n\nTarget Lessons Structure:\nThe teacher has requested to create exactly {len(req.custom_lessons)} lessons, with these exact titles and sub-topics in this order:\n"
            for i, l in enumerate(req.custom_lessons):
                custom_lessons_instruction += f"- Lesson {i+1}: \"{l.title}\"\n  Topics to cover in this lesson:\n"
                for t in l.topics:
                    custom_lessons_instruction += f"    * {t}\n"
            custom_lessons_instruction += "\nInstruction: You MUST structure the curriculum lessons list to match this exact list of lessons. For each lesson, generate the appropriate pedagogical modules sequence (UNDERSTAND, APPLY, etc.) covering the specific sub-topics listed for that lesson."

        lessons_count_instruction = f"Lessons Count: {req.lessons_count}" if req.lessons_count > 0 else "Lessons Count: [AI, please determine the optimal number of lessons (typically between 3 and 12) based on the depth of the course topic or the length of the PDF content. Design a complete, self-contained curriculum with that optimal number of lessons.]"

        prompt = f"""
Role: You are an expert instructional designer and curriculum planner. Türkçe cevap ver.
Your task is only to design the structure of a learning roadmap (lessons and modules sequence).
{pdf_context}
{custom_lessons_instruction}

Goal: Given the course topic, difficulty, desired lesson count, target audience, and target lessons list, generate the sequence of lessons and modules.

Requirements:
- The roadmap consists of lessons.
- Each lesson contains a list of modules representing levels.
- Modules are selected from: UNDERSTAND, APPLY, CONNECT, CREATE, QUIZ, HOMEWORK.
- **FLEXIBLE PEDAGOGICAL FLOW & MODULE RULES**:
  - A lesson can cover 1 or MULTIPLE sub-topics.
  - For EACH distinct sub-topic taught in the lesson, generate a pair of `UNDERSTAND` (Anla - Konu Teorisi) followed immediately by `APPLY` (Uygula - Kodlama Pratiği).
  - Therefore, a lesson CAN contain MULTIPLE `UNDERSTAND` and `APPLY` pairs if there are multiple sub-topics in that lesson (e.g., `UNDERSTAND(Konu 1) -> APPLY(Konu 1) -> UNDERSTAND(Konu 2) -> APPLY(Konu 2)...`). Do NOT limit a lesson to only one pair if multiple concepts are taught!
  - After all sub-topic theory & practice pairs in the lesson, you MUST include:
    1. At least one `CONNECT` module (Birleştir - Öğrenilen Kavramları Birleştirme Görevi / Bulmaca)
    2. At least one `CREATE` module (Üret - Mini Proje / Üretim Görevi)
    3. Exactly one `QUIZ` or `HOMEWORK` module (Değerlendirme Testi veya Ödev)
  - Summary of lesson module sequence: `[(UNDERSTAND -> APPLY)* (1 or more pairs)] -> CONNECT -> CREATE -> QUIZ (or HOMEWORK)`.
- **CRITICAL TITLE LENGTH CONSTRAINT (STRICT RULE)**: Every lesson title (`title`) and module topic string (`topic`) MUST be concise and MUST NOT exceed 30 characters in total length (e.g., 'Python Kurulumu', 'Değişken Tanımlama', 'Koşullu İfadeler'). Never generate verbose or long titles exceeding 30 characters.
- Each module in the lessons modules list MUST have a specific, distinct `"topic"` string explaining what specific sub-topic or task this module covers. This is critical for generating unique slide contents later.
- Return ONLY valid JSON matching the structure below. No markdown formatting, no text before or after the JSON.

Expected JSON Structure:
{{
  "courseTitle": "...",
  "lessons": [
    {{
      "lessonNumber": 1,
      "title": "Lesson title (Türkçe)",
      "objective": "Lesson learning objective (Türkçe)",
      "modules": [
        {{ "type": "UNDERSTAND", "topic": "1. Konu Anlatımı Başlığı (Türkçe)" }},
        {{ "type": "APPLY", "topic": "1. Konu Kodlama Pratiği Görevi (Türkçe)" }},
        {{ "type": "UNDERSTAND", "topic": "2. Konu Anlatımı Başlığı (Varsa) (Türkçe)" }},
        {{ "type": "APPLY", "topic": "2. Konu Kodlama Pratiği Görevi (Varsa) (Türkçe)" }},
        {{ "type": "CONNECT", "topic": "Öğrenilen Tüm Kavramları Birleştirme Görevi (Türkçe)" }},
        {{ "type": "CREATE", "topic": "Mini Proje Üretim Görevi (Türkçe)" }},
        {{ "type": "QUIZ", "topic": "Ders Değerlendirme Testi (Türkçe)" }}
      ]
    }}
  ]
}}

Input:
Topic: {req.topic}
Difficulty: {req.difficulty}
{lessons_count_instruction}
Audience: {req.audience}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=RoadmapStructureResponse
            )
        )
        await record_ai_usage(db, teacher_id, "generate_roadmap_structure", "gemini-2.5-flash", response, details=f"Kurs: '{req.topic}' ({req.lessons_count} Ders İskeleti)")
        
        data = json.loads(response.text.strip())
        return {"success": True, "roadmap": data}
    except Exception as e:
        print(f"Error planning roadmap structure: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/suggest_lesson_modules")
async def suggest_lesson_modules_api(
    req: SuggestLessonModulesRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    try:
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        pdf_context = ""
        if req.pdf_content:
            pdf_context = f"\n\nSource Material (PDF Content):\n{req.pdf_content[:30000]}\n\nInstruction: Base the lesson objective and modular topic titles strictly on the provided Source Material PDF above."
            
        prompt = f"""
Role: You are an expert instructional designer and curriculum planner. Türkçe cevap ver.
Your task is to design the sub-modules (levels) for a single lesson in a learning roadmap.
{pdf_context}

Course Context:
Main Course Topic: {req.course_topic}
Course Difficulty: {req.difficulty}
Target Audience: {req.audience}

Lesson to design:
Lesson Title: {req.lesson_title}

Requirements:
- Plan the modules sequence for this lesson.
- Modules are selected from: UNDERSTAND, APPLY, CONNECT, CREATE, QUIZ, HOMEWORK.
- **FLEXIBLE PEDAGOGICAL FLOW & MODULE RULES**:
  - A lesson can cover 1 or MULTIPLE sub-topics.
  - For EACH distinct sub-topic taught in the lesson, generate a pair of `UNDERSTAND` (Anla - Konu Teorisi) followed immediately by `APPLY` (Uygula - Kodlama Pratiği).
  - Therefore, a lesson CAN contain MULTIPLE `UNDERSTAND` and `APPLY` pairs if there are multiple sub-topics in that lesson (e.g., `UNDERSTAND(Konu 1) -> APPLY(Konu 1) -> UNDERSTAND(Konu 2) -> APPLY(Konu 2)...`). Do NOT limit a lesson to only one pair if multiple concepts are taught!
  - After all sub-topic theory & practice pairs in the lesson, you MUST include:
    1. At least one `CONNECT` module (Birleştir - Öğrenilen Kavramları Birleştirme Görevi / Bulmaca)
    2. At least one `CREATE` module (Üret - Mini Proje / Üretim Görevi)
    3. Exactly one `QUIZ` or `HOMEWORK` module (Değerlendirme Testi veya Ödev)
  - Summary of lesson module sequence: `[(UNDERSTAND -> APPLY)* (1 or more pairs)] -> CONNECT -> CREATE -> QUIZ (or HOMEWORK)`.
- YOU MUST NEVER OMIT CONNECT OR CREATE MODULES!
- Each module in the modules list MUST have a specific, distinct `"topic"` string explaining what specific sub-topic or task this module covers. This is critical for generating unique slide contents later.
- Return ONLY valid JSON matching the structure below. No markdown formatting, no text before or after the JSON.

Expected JSON Structure:
{{
  "objective": "Lesson learning objective (Türkçe)",
  "modules": [
    {{ "type": "UNDERSTAND", "topic": "1. Konu Anlatımı Başlığı (Türkçe)" }},
    {{ "type": "APPLY", "topic": "1. Konu Kodlama Pratiği Görevi (Türkçe)" }},
    {{ "type": "UNDERSTAND", "topic": "2. Konu Anlatımı Başlığı (Varsa) (Türkçe)" }},
    {{ "type": "APPLY", "topic": "2. Konu Kodlama Pratiği Görevi (Varsa) (Türkçe)" }},
    {{ "type": "CONNECT", "topic": "Öğrenilen Tüm Kavramları Birleştirme Görevi (Türkçe)" }},
    {{ "type": "CREATE", "topic": "Mini Proje Üretim Görevi (Türkçe)" }},
    {{ "type": "QUIZ", "topic": "Ders Değerlendirme Testi (Türkçe)" }}
  ]
}}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=SuggestLessonModulesResponse
            )
        )
        await record_ai_usage(db, teacher_id, "suggest_lesson_modules", "gemini-2.5-flash", response, details=f"Kurs: '{req.course_topic}' | Ders: '{req.lesson_title}'")
        
        data = json.loads(response.text.strip())
        return {"success": True, "objective": data.get("objective"), "modules": data.get("modules", [])}
    except Exception as e:
        print(f"Error suggesting lesson modules: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/suggest_lesson_title")
async def suggest_lesson_title_api(
    req: SuggestLessonTitleRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    try:
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        # Calculate preceding and succeeding lessons for clear contextual instruction
        preceding = req.existing_lessons[req.lesson_number - 2] if req.lesson_number > 1 and len(req.existing_lessons) >= req.lesson_number - 1 else None
        succeeding = req.existing_lessons[req.lesson_number] if len(req.existing_lessons) > req.lesson_number else None
        
        pdf_context = ""
        if req.pdf_content:
            pdf_context = f"\n\nSource Material (PDF Content):\n{req.pdf_content[:30000]}\n\nInstruction: Base the title suggestions strictly on the provided Source Material PDF content above."

        prompt = f"""
Role: You are an expert instructional designer and computer science curriculum planner. Türkçe cevap ver.
Your task is to suggest 5 alternative relevant lesson titles for lesson number {req.lesson_number} in a course curriculum.
{pdf_context}

Course Context:
Main Course Topic: {req.course_topic}
Course Difficulty: {req.difficulty}
Target Audience: {req.audience}

Curriculum Context:
Full Current Lesson Titles Sequence: {json.dumps(req.existing_lessons, ensure_ascii=False)}
Lesson Number to suggest: {req.lesson_number}
Preceding Lesson Title: {f'"{preceding}"' if preceding else "Yok (İlk Ders)"}
Succeeding Lesson Title: {f'"{succeeding}"' if succeeding else "Yok (Son Ders)"}

Requirements:
1. Suggest exactly 5 distinct, highly logical alternative lesson titles (in Turkish) for lesson number {req.lesson_number}.
2. Crucially check the surrounding titles: the suggested title MUST bridge the gap between the preceding lesson ("{preceding or ''}") and the succeeding lesson ("{succeeding or ''}").
3. For example:
   - If preceding is "Değişkenler" (variables) and succeeding is "Döngüler" (loops), the most standard and logical bridge topic in programming is "Koşullu İfadeler / Karar Yapıları (if-else, karşılaştırma operatörleri)".
   - Do NOT jump directly to advanced topics, and do NOT repeat concepts already covered in preceding/succeeding lessons.
4. Return ONLY valid JSON matching the structure below. No markdown formatting.

Expected JSON Structure:
{{
  "titles": [
    "Alternative Title 1",
    "Alternative Title 2",
    "Alternative Title 3",
    "Alternative Title 4",
    "Alternative Title 5"
  ]
}}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=SuggestLessonTitleResponse
            )
        )
        await record_ai_usage(db, teacher_id, "suggest_lesson_title", "gemini-2.5-flash", response, details=f"Kurs: '{req.course_topic}' | Ders {req.lesson_number} Başlık Önerisi")
        data = json.loads(response.text.strip())
        return {"success": True, "titles": data.get("titles", [])}
    except Exception as e:
        print(f"Error suggesting lesson title: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/suggest_level_details")
async def suggest_level_details_api(
    req: SuggestLevelDetailsRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    try:
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        pdf_context = ""
        if req.pdf_content:
            pdf_context = f"\n\nSource Material (PDF Content):\n{req.pdf_content[:30000]}\n\nInstruction: Base the module title and topic suggestions strictly on the provided Source Material PDF content above."

        prompt = f"""
Role: You are an expert instructional designer. Türkçe cevap ver.
Your task is to suggest the title and detailed topic content for a specific module (level) inside a lesson.
{pdf_context}

Course Context:
Main Course Topic: {req.course_topic}
Difficulty: {req.difficulty}
Audience: {req.audience}

Lesson Context:
Lesson Title: {req.lesson_title}

Module Context:
Type of module: {req.module_type} (UNDERSTAND = theory, APPLY = practice challenge, CONNECT = combine concepts, CREATE = mini project, QUIZ = topic quiz, HOMEWORK = homework assignment)
Other modules already planned in this lesson: {json.dumps(req.sibling_modules, ensure_ascii=False)}

Requirements:
- Suggest a short display title (CRITICAL: MUST NOT exceed 30 characters) and a detailed description/topic (1-2 sentences) of what should be taught/practiced in this module.
- It must be relevant to both the lesson title and the pedagogical module type.
- Avoid repeating topics that are already covered by sibling modules.
- Return ONLY valid JSON matching the structure below. No markdown formatting.

Expected JSON Structure:
{{
  "title": "Short title (Türkçe)",
  "topic": "Detailed description / coding task prompt (Türkçe)"
}}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=SuggestLevelDetailsResponse
            )
        )
        await record_ai_usage(db, teacher_id, "suggest_level_details", "gemini-2.5-flash", response, details=f"Kurs: '{req.course_topic}' | Ders: '{req.lesson_title}' | Modül: {req.module_type}")
        data = json.loads(response.text.strip())
        return {"success": True, "title": data.get("title"), "topic": data.get("topic")}
    except Exception as e:
        print(f"Error suggesting level details: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/courses/generate_lesson_slides")
async def generate_lesson_slides_api(
    req: GenerateLessonSlidesRequest,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    TEMPLATES_PATH = "slide_templates.json"
    
    try:
        # Load templates
        templates = []
        if os.path.exists(TEMPLATES_PATH):
            with open(TEMPLATES_PATH, "r", encoding="utf-8") as f:
                templates = json.load(f)
                
        # Group templates by category
        templates_by_category = {
            "ANLA": [],
            "UYGULA": [],
            "BİRLEŞTİR": [],
            "ÜRET": []
        }
        for t in templates:
            cat = t.get("category", "").upper()
            if cat in templates_by_category:
                elements_info = []
                for el in t.get("elements", []):
                    if el.get("type") in ["text", "code", "sticky", "challenge", "code_editor", "connection_task", "production_task", "image"]:
                        elements_info.append({
                            "id": el.get("id"),
                            "type": el.get("type"),
                            "placeholder": el.get("content"),
                            "maxChars": el.get("maxChars")
                        })
                templates_by_category[cat].append({
                    "id": t.get("id"),
                    "title": t.get("title"),
                    "description": t.get("description"),
                    "elements": elements_info
                })
                
        client = genai.Client(api_key=settings.MY_API_KEY)
        
        pdf_context = ""
        if req.pdf_content:
            pdf_context = f"\n\nSource Material (PDF Content):\n{req.pdf_content[:30000]}\n\nInstruction: Base the slide contents, descriptions, explanations, code snippets, quizzes, and homework topics strictly on the provided Source Material PDF above."

        prompt = f"""
Role: You are an expert instructional designer and curriculum planner. Türkçe cevap ver.
Your task is to write detailed educational slide, quiz, and homework contents for the UNDERSTAND, APPLY, CONNECT, and CREATE modules in the provided single lesson.
{pdf_context}

Course context:
Topic: {req.topic}
Difficulty: {req.difficulty}
Audience: {req.audience}

Lesson to populate:
Lesson Number: {req.lesson_number}
Lesson Title: {req.lesson_title}
Lesson Objective: {req.lesson_objective}
Modules list: {json.dumps(req.modules, ensure_ascii=False)}

Available Templates for each category:
- UNDERSTAND (ANLA) templates:
{format_templates_summary(templates_by_category["ANLA"])}

- APPLY (UYGULA) templates:
{format_templates_summary(templates_by_category["UYGULA"])}

- CONNECT (BİRLEŞTİR) templates:
{format_templates_summary(templates_by_category["BİRLEŞTİR"])}

- CREATE (ÜRET) templates:
{format_templates_summary(templates_by_category["ÜRET"])}

Requirements:
- For each module in the lesson of type UNDERSTAND, APPLY, CONNECT, and CREATE, you MUST generate slide contents.
- For each module, choose the most suitable template from the available templates of its category.
- UNIVERSAL PEDAGOGICAL RULE FOR ALL TOPICS (STRICT CONSTRAINT):
  * For UNDERSTAND (ANLA): Generate 2 to 4 slides explaining the lesson concepts. Crucially, EVERY single concept, formula, syntax, method, command, tool, function, or technique that will be required or practiced in the subsequent APPLY module MUST be explicitly taught, explained, and demonstrated with a concrete example (code block, text example, or formula breakdown) in these UNDERSTAND slides. Never explain theory without showing a concrete working example.
  * For APPLY (UYGULA): Generate 1 to 2 slides with task instructions or challenges. The student MUST ONLY be asked to apply or solve what was explicitly demonstrated and taught in the immediately preceding UNDERSTAND slides. It is STRICTLY FORBIDDEN to introduce or ask for any new concept, syntax, method, function, or formula in APPLY that was not explicitly shown in UNDERSTAND.
- For CONNECT (BİRLEŞTİR): This module MUST NOT teach new theory, MUST NOT use daily life analogies, and MUST NOT provide concept definitions. Its ONLY goal is to make the student combine and use two or more previously learned concepts together in a single coding challenge. 
  * In the Connection Task template, the `connection_task` element content MUST be a JSON-serialized string formatted exactly like this to populate the connection task widget:
    {{"previousTopic": "Name of previous topic (e.g. Değişken Tanımlama)", "currentTopic": "Name of current topic (e.g. Koşullu İfadeler)", "taskText": "Detailed connection coding challenge instructions asking the student to combine both topics."}}
- For CREATE (ÜRET): This module is for building a small mini-project.
  * In the Produce Task template, the `production_task` element content MUST be a JSON-serialized string formatted exactly like this to populate the production task widget:
    {{"projectTitle": "Title of the project (e.g. Hesap Makinesi)", "taskText": "Detailed instructions on what to build", "expectedOutput": "Example console output showing what the running code should display", "estimatedTime": "Estimated completion time (e.g. 15 Dakika)", "hints": "Useful coding hint or tip"}}
  * Note: The JSON string for `connection_task` or `production_task` must be escaped properly so that it is a valid JSON string inside the outer JSON response. Escape double quotes with `\"` and use `\n` for line breaks. Do not write raw newlines inside the string values.
- For QUIZ: generate 3 multiple-choice questions about the lesson topic. Each question must have 1 correct option and 3 incorrect options.
- For HOMEWORK: generate 1 practical homework task. Decide if the student should submit code, text, image, or file.
  * For programming topics, use "code" submissionType. For conceptual tasks, use "text".
  * For "code" type: provide a small starterCode template.
- CRITICAL IMAGE REQUIREMENT: Your templates contain "image" elements. For EVERY "image" element, you MUST populate the "content" field in "elementContents" with a descriptive English search query (3-5 words) representing the visual content for that specific slide (e.g., "ancient roman soldier armor" for a history slide, "python coding mathematical operator" for a programming slide, "cell division biology microscope" for a biology slide). DO NOT leave "image" elements empty or unpopulated.
- For each element you populate in `elementContents`, you MUST strictly respect the `maxChars` limit defined in the template. The number of characters of your generated text (including spaces) for that element ID MUST NOT exceed its `maxChars` value to prevent UI text overflow. This is a critical visual layout constraint.
- Populate `elementContents` mapping the template element IDs to your generated educational contents in Turkish.
- Return ONLY valid JSON matching the structure below. No markdown formatting, no text before or after the JSON.

Expected JSON Structure:
{{
  "modules_content": [
    {{
      "lessonNumber": {req.lesson_number},
      "moduleIndex": 0, // 0-based index of the module in the lesson's modules list
      "slides": [
        {{
          "selectedTemplateId": "template_id_here",
          "elementContents": [
             {{ "elementId": "element_id_1", "content": "Generated text explanation in Turkish" }},
             {{ "elementId": "element_id_2", "content": "Generated python code or note..." }}
          ]
        }}
      ]
    }}
  ],
  "quiz_map": [
    {{
      "questionText": "Question text in Turkish?",
      "options": [
        {{ "text": "Correct Option text in Turkish", "isCorrect": true }},
        {{ "text": "Incorrect Option text in Turkish", "isCorrect": false }},
        {{ "text": "Another Incorrect Option", "isCorrect": false }},
        {{ "text": "Another Incorrect Option", "isCorrect": false }}
      ]
    }}
  ],
  "homework_map": {{
    "title": "Homework Title in Turkish",
    "instructions": "Step-by-step homework instructions/questions in Turkish",
    "submissionType": "code",
    "points": 100,
    "starterCode": "# Write starter code or comment template here in Turkish"
  }}
}}
"""
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=LessonSlidesResponse
            )
        )
        await record_ai_usage(db, teacher_id, "generate_lesson_slides", "gemini-2.5-flash", response, details=f"Kurs: '{req.topic}' | Ders {req.lesson_number}: '{req.lesson_title}' | Modül Sayısı: {len(req.modules)}")
        
        slide_contents_data = json.loads(response.text.strip())
        modules_content = slide_contents_data.get("modules_content") or []
        
        # Build slides and notes
        theme_map = {
          "UNDERSTAND": "purple",
          "APPLY": "cyan",
          "CONNECT": "green",
          "CREATE": "yellow",
          "QUIZ": "quiz",
          "HOMEWORK": "homework"
        }
        
        all_templates_map = {
            "UNDERSTAND": templates_by_category["ANLA"],
            "APPLY": templates_by_category["UYGULA"],
            "CONNECT": templates_by_category["BİRLEŞTİR"],
            "CREATE": templates_by_category["ÜRET"]
        }
        
        generated_modules = []
        generated_notes = []
        
        for m_idx, mod in enumerate(req.modules):
            mod_type = mod.get("type", "UNDERSTAND").upper()
            mapped_theme = theme_map.get(mod_type, "purple")
            level_id = f"sec_ai_{int(random.random() * 1000000000)}"
            
            node = {
              "id": level_id,
              "title": mod.get("topic") or "" if mod_type not in ["QUIZ", "HOMEWORK"] else ("Konu Testi" if mod_type == "QUIZ" else "Ödev Görevi"),
              "theme": mapped_theme,
              "lectures": []
            }
            
            if m_idx == 0:
              node["lessonTopic"] = req.lesson_title
              node["lessonNumber"] = req.lesson_number
              
            generated_modules.append(node)
            
            if mod_type in ["UNDERSTAND", "APPLY", "CONNECT", "CREATE"]:
                # Find matching generated slides by moduleIndex
                matched = next((
                    mc for mc in modules_content 
                    if str(mc.get("moduleIndex")) == str(m_idx)
                ), None)
                
                ai_slides = []
                if matched:
                    ai_slides = matched.get("slides") or []
                    
                cat_templates = all_templates_map.get(mod_type, [])
                
                # Fallback if empty but templates exist
                if not ai_slides and cat_templates:
                    ai_slides = [{"selectedTemplateId": cat_templates[0]["id"], "elementContents": {}}]
                    
                if isinstance(ai_slides, dict):
                    ai_slides = [ai_slides]
                elif not isinstance(ai_slides, list):
                    ai_slides = []
                    
                slides_to_add = []
                for ai_slide in ai_slides:
                    sel_template_id = ai_slide.get("selectedTemplateId")
                    raw_contents = ai_slide.get("elementContents") or []
                    elem_contents = {}
                    if isinstance(raw_contents, list):
                        for pair in raw_contents:
                            if isinstance(pair, dict) and "elementId" in pair:
                                elem_contents[pair["elementId"]] = pair.get("content") or ""
                    elif isinstance(raw_contents, dict):
                        elem_contents = raw_contents
                    
                    # Find original template elements
                    selected_t = next((t for t in templates if t.get("id") == sel_template_id), None)
                    # Fallback to category template if not found
                    if not selected_t and cat_templates:
                        selected_t = next((t for t in templates if t.get("id") == cat_templates[0]["id"]), None)
                        
                    if selected_t:
                        copied_elements = []
                        for el in selected_t.get("elements", []):
                            el_copy = copy.deepcopy(el)
                            el_id = el_copy.get("id")
                            el_type = el_copy.get("type")
                            
                            # Pre-evaluate value if present
                            val = elem_contents.get(el_id) if el_id in elem_contents else ""
                            
                            if el_type == "image":
                                # Determine query - fallback to module topic or lesson title if empty
                                query = val if val else (mod.get("topic") or req.lesson_title or "coding")
                                is_fb = not bool(val)
                                img_url = get_web_image(query, is_fallback=is_fb)
                                el_copy["content"] = img_url
                                el_copy["imageUrl"] = img_url
                                el_copy["src"] = img_url
                            elif el_id in elem_contents:
                                if el_type == "connection_task":
                                    import json as pyjson
                                    try:
                                        parsed = pyjson.loads(val)
                                        el_copy["content"] = parsed.get("taskText") or val
                                        if "extra" not in el_copy or not el_copy["extra"]:
                                            el_copy["extra"] = {}
                                        el_copy["extra"]["previousTopic"] = parsed.get("previousTopic") or "Önceki Konu"
                                        el_copy["extra"]["currentTopic"] = parsed.get("currentTopic") or "Şimdiki Konu"
                                    except Exception:
                                        el_copy["content"] = val
                                elif el_type == "production_task":
                                    import json as pyjson
                                    try:
                                        parsed = pyjson.loads(val)
                                        el_copy["content"] = parsed.get("taskText") or val
                                        if "extra" not in el_copy or not el_copy["extra"]:
                                            el_copy["extra"] = {}
                                        el_copy["extra"]["projectTitle"] = parsed.get("projectTitle") or "Proje Başlığı"
                                        el_copy["extra"]["expectedOutput"] = parsed.get("expectedOutput") or ""
                                        el_copy["extra"]["estimatedTime"] = parsed.get("estimatedTime") or "10 Dakika"
                                        el_copy["extra"]["hints"] = parsed.get("hints") or ""
                                    except Exception:
                                        el_copy["content"] = val
                                else:
                                    el_copy["content"] = val
                            
                            copied_elements.append(el_copy)
                            
                        slide = {
                            "id": int(random.random() * 1000000000),
                            "elements": copied_elements,
                            "background": selected_t.get("background", "default")
                        }
                        slides_to_add.append(slide)
                        
                if slides_to_add:
                    note = {
                        "id": level_id,
                        "noteTitle": "",
                        "slides": slides_to_add
                    }
                    generated_notes.append(note)
            
            elif mod_type == "QUIZ":
                quiz_questions = slide_contents_data.get("quiz_map") or []
                questions_list = []
                
                if quiz_questions:
                    for idx, qq in enumerate(quiz_questions):
                        options_list = []
                        for opt_idx, opt in enumerate(qq.get("options", [])):
                            options_list.append({
                                "id": str(opt_idx + 1),
                                "text": opt.get("text", ""),
                                "isCorrect": opt.get("isCorrect", False)
                            })
                        questions_list.append({
                            "id": f"q-{idx + 1}-{int(random.random() * 100000)}",
                            "text": qq.get("questionText", "Soru"),
                            "options": options_list
                        })
                
                # Fallback if empty
                if not questions_list:
                    questions_list = [{
                        "id": "mock-q-1",
                        "text": f"{req.lesson_title} Konu Değerlendirme Sorusu",
                        "options": [
                            { "id": "1", "text": "Doğru Seçenek", "isCorrect": true },
                            { "id": "2", "text": "Yanlış Seçenek 1", "isCorrect": false },
                            { "id": "3", "text": "Yanlış Seçenek 2", "isCorrect": false },
                            { "id": "4", "text": "Yanlış Seçenek 3", "isCorrect": false }
                        ]
                    }]
                
                quiz_slide = {
                    "id": int(random.random() * 1000000000),
                    "type": "game",
                    "gameType": "matching",
                    "gameConfig": {
                        "timeLimit": 60,
                        "questions": questions_list
                    },
                    "elements": []
                }
                
                note = {
                    "id": level_id,
                    "noteTitle": "",
                    "slides": [quiz_slide]
                }
                generated_notes.append(note)
            
            elif mod_type == "HOMEWORK":
                hw_data = slide_contents_data.get("homework_map") or {}
                hw_title = hw_data.get("title") or f"{req.lesson_title} Ödev Görevi"
                hw_instructions = hw_data.get("instructions") or "Lütfen bu konuyla ilgili ödevinizi tamamlayıp yükleyin."
                hw_sub_type = hw_data.get("submissionType") or "text"
                hw_points = hw_data.get("points") or 100
                hw_starter = hw_data.get("starterCode") or "# Kodunuzu buraya yazın\n"
                
                homework_slide = {
                    "id": int(random.random() * 1000000000),
                    "type": "homework",
                    "background": "default",
                    "homeworkConfig": {
                        "title": hw_title,
                        "instructions": hw_instructions,
                        "submissionType": hw_sub_type,
                        "points": hw_points,
                        "starterCode": hw_starter
                    },
                    "elements": []
                }
                
                note = {
                    "id": level_id,
                    "noteTitle": "",
                    "slides": [homework_slide]
                }
                generated_notes.append(note)
                    
        return {"success": True, "modules": generated_modules, "notes": generated_notes}
    except Exception as e:
        print(f"Error generating lesson slides: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/ai/metrics")
@router.get("/courses/metrics")
async def get_ai_metrics_api(
    db: AsyncSession = Depends(get_db),
    user_info: dict = Depends(get_current_user_info)
):
    """
    Eğitmen veya Admin paneli için Yapay Zeka (AI) kullanım metriklerini ve harcama özetini döndürür.
    """
    if user_info.get("role") not in ["admin", "teacher", "instructor"]:
        raise HTTPException(status_code=403, detail="Erişim yetkiniz bulunmamaktadır.")

    result = await db.execute(select(AIUsageLog).order_by(AIUsageLog.created_at.desc()))
    logs = result.scalars().all()

    total_requests = len(logs)
    total_prompt_tokens = sum(l.prompt_tokens or 0 for l in logs)
    total_candidates_tokens = sum(l.candidates_tokens or 0 for l in logs)
    total_tokens = total_prompt_tokens + total_candidates_tokens
    
    # Calculate official Google AI Studio cost ($0.30 / 1M input, $2.50 / 1M output)
    rate_input = 0.30 / 1_000_000
    rate_output = 2.50 / 1_000_000
    total_cost_usd = (total_prompt_tokens * rate_input) + (total_candidates_tokens * rate_output)
    usd_to_tl_rate = 38.0
    total_cost_tl = total_cost_usd * usd_to_tl_rate

    by_action = {}
    by_model = {}
    by_course = {}

    for l in logs:
        p_tok = l.prompt_tokens or 0
        c_tok = l.candidates_tokens or 0
        t_tok = p_tok + c_tok if (p_tok or c_tok) else (l.total_tokens or 0)
        c_usd = (p_tok * rate_input) + (c_tok * rate_output) if (p_tok or c_tok) else (l.cost_usd or 0.0)

        act = l.action or "diğer"
        if act not in by_action:
            by_action[act] = {"count": 0, "tokens": 0, "cost_usd": 0.0}
        by_action[act]["count"] += 1
        by_action[act]["tokens"] += t_tok
        by_action[act]["cost_usd"] += c_usd

        mdl = l.model_name or "bilinmiyor"
        if mdl not in by_model:
            by_model[mdl] = {"count": 0, "tokens": 0, "cost_usd": 0.0}
        by_model[mdl]["count"] += 1
        by_model[mdl]["tokens"] += t_tok
        by_model[mdl]["cost_usd"] += c_usd

        # Course grouping
        c_name = getattr(l, "course_title", None)
        if not c_name and l.details:
            match = re.search(r"Kurs:\s*'([^']+)'", l.details) or re.search(r"Kurs:\s*([^|]+)", l.details)
            if match:
                c_name = match.group(1).strip()
        
        if not c_name:
            c_name = "Genel / Bağımsız İşlemler"

        if c_name not in by_course:
            by_course[c_name] = {
                "course_title": c_name,
                "course_id": getattr(l, "course_id", None),
                "total_calls": 0,
                "prompt_tokens": 0,
                "candidates_tokens": 0,
                "total_tokens": 0,
                "cost_usd": 0.0,
                "cost_tl": 0.0,
                "steps": []
            }

        by_course[c_name]["total_calls"] += 1
        by_course[c_name]["prompt_tokens"] += p_tok
        by_course[c_name]["candidates_tokens"] += c_tok
        by_course[c_name]["total_tokens"] += t_tok
        by_course[c_name]["cost_usd"] += c_usd

        by_course[c_name]["steps"].append({
            "id": l.id,
            "action": l.action,
            "model_name": l.model_name,
            "prompt_tokens": p_tok,
            "candidates_tokens": c_tok,
            "total_tokens": t_tok,
            "cost_usd": round(c_usd, 6),
            "details": getattr(l, "details", None),
            "created_at": l.created_at.isoformat() if l.created_at else None
        })

    # Format course summaries
    courses_summary = []
    for c_info in by_course.values():
        c_info["cost_tl"] = round(c_info["cost_usd"] * usd_to_tl_rate, 2)
        c_info["cost_usd"] = round(c_info["cost_usd"], 6)
        courses_summary.append(c_info)

    courses_summary.sort(key=lambda x: x["cost_usd"], reverse=True)

    recent_logs = [
        {
            "id": l.id,
            "teacher_id": l.teacher_id,
            "action": l.action,
            "model_name": l.model_name,
            "prompt_tokens": l.prompt_tokens or 0,
            "candidates_tokens": l.candidates_tokens or 0,
            "total_tokens": (l.prompt_tokens or 0) + (l.candidates_tokens or 0) if (l.prompt_tokens or l.candidates_tokens) else (l.total_tokens or 0),
            "cost_usd": round(l.cost_usd or 0.0, 6),
            "details": getattr(l, "details", None),
            "created_at": l.created_at.isoformat() if l.created_at else None
        }
        for l in logs[:100]
    ]

    return {
        "success": True,
        "metrics": {
            "total_requests": total_requests,
            "total_prompt_tokens": total_prompt_tokens,
            "total_candidates_tokens": total_candidates_tokens,
            "total_tokens": total_tokens,
            "total_cost_usd": round(total_cost_usd, 4),
            "total_cost_tl": round(total_cost_tl, 2),
            "usd_to_tl_rate": usd_to_tl_rate,
            "by_action": by_action,
            "by_model": by_model,
            "by_course": courses_summary,
            "recent_logs": recent_logs
        }
    }


@router.delete("/ai/metrics")
@router.delete("/courses/metrics")
async def clear_ai_metrics_api(
    db: AsyncSession = Depends(get_db),
    user_info: dict = Depends(get_current_user_info)
):
    """
    Tüm Yapay Zeka (AI) metrik ve kullanım loglarını sıfırlar / siler.
    """
    if user_info.get("role") not in ["admin", "teacher", "instructor"]:
        raise HTTPException(status_code=403, detail="Erişim yetkiniz bulunmamaktadır.")

    await db.execute(delete(AIUsageLog))
    await db.commit()

    return {
        "success": True,
        "message": "Tüm yapay zeka metrik verileri sıfırlandı."
    }


def get_module_type_from_theme_py(theme: str) -> str:
    if not theme:
        return "UNDERSTAND"
    t = theme.lower()
    if t == "purple": return "UNDERSTAND"
    if t == "cyan": return "APPLY"
    if t == "green": return "CONNECT"
    if t == "yellow": return "CREATE"
    if t == "quiz": return "QUIZ"
    if t == "homework": return "HOMEWORK"
    return "UNDERSTAND"


class StartBackgroundGenerationRequest(BaseModel):
    topic: str
    difficulty: str = "Beginner"
    audience: str = "Hiç kodlama deneyimi olmayan öğrenciler."
    chapters: List[Dict[str, Any]]
    pdf_content: Optional[str] = None


async def run_background_slide_generation(
    course_id: int,
    teacher_id: int,
    topic: str,
    difficulty: str,
    audience: str,
    chapters: List[Dict[str, Any]],
    pdf_content: Optional[str] = None
):
    """
    Background worker that runs slide generation lesson-by-lesson asynchronously on FastAPI server.
    Updates DB after each completed lesson. Survives browser refresh and disconnects.
    """
    async with SessionLocal() as db:
        try:
            res = await db.execute(select(Course).where(Course.id == course_id, Course.teacher_id == teacher_id))
            course = res.scalars().first()
            if not course:
                return

            curriculum = list(course.curriculum or [])
            all_notes = list(course.notes or [])
            total_chapters = len(chapters)
            overall_idx = 1

            for i, chapter in enumerate(chapters):
                status_item = {
                    "type": "ai_generation_status",
                    "status": "processing",
                    "current": i + 1,
                    "total": total_chapters,
                    "message": f"Ders {i + 1}/{total_chapters}: '{chapter.get('topic')}' slaytları hazırlanıyor..."
                }

                curriculum = [c for c in curriculum if c.get("type") != "ai_generation_status"]
                curriculum.append(status_item)

                course.curriculum = list(curriculum)
                db.add(course)
                await db.commit()

                modules_input = [
                    {"type": get_module_type_from_theme_py(lvl.get("theme")), "topic": lvl.get("title")}
                    for lvl in chapter.get("levels", [])
                ]
                objective = chapter.get("levels", [{}])[0].get("aiLessonObjective") or f"Bu derste {chapter.get('topic')} konusu öğrenilecektir."

                req_obj = GenerateLessonSlidesRequest(
                    topic=topic,
                    difficulty=difficulty,
                    audience=audience,
                    lesson_number=chapter.get("number", i + 1),
                    lesson_title=chapter.get("topic", f"Ders {i+1}"),
                    lesson_objective=objective,
                    modules=modules_input,
                    pdf_content=pdf_content
                )

                slide_res = await generate_lesson_slides_api(req_obj, teacher_id=teacher_id, db=db)
                returned_modules = slide_res.get("modules", [])
                returned_notes = slide_res.get("notes", [])

                orig_levels = chapter.get("levels", [])
                for n_idx, node in enumerate(returned_modules):
                    orig_level = orig_levels[n_idx] if n_idx < len(orig_levels) else {}
                    real_title = orig_level.get("title") or orig_level.get("aiModuleTopic") or node.get("topic") or node.get("title")
                    
                    clean_t = re.sub(r"^(?:Ders\s+\d+[:\s\-]*|\d+[\.\)\s\-]*)", "", str(real_title), flags=re.IGNORECASE).strip()
                    node["title"] = clean_t[:30] if clean_t else f"Modül {overall_idx}"
                    overall_idx += 1
                    node.pop("isAIDraft", None)
                    node.pop("isAILoading", None)

                for note in returned_notes:
                    matched_node = next((nm for nm in returned_modules if nm.get("id") == note.get("id")), None)
                    if matched_node:
                        note["noteTitle"] = matched_node.get("title")

                all_notes.extend(returned_notes)

                chapter_level_ids = [l.get("id") for l in orig_levels]
                clean_curr = [c for c in curriculum if c.get("type") != "ai_generation_status"]
                
                first_idx = next((idx for idx, s in enumerate(clean_curr) if s.get("id") in chapter_level_ids), -1)
                if first_idx != -1:
                    clean_curr[first_idx:first_idx + len(chapter_level_ids)] = returned_modules
                
                curriculum = clean_curr

                course.curriculum = list(curriculum)
                course.notes = list(all_notes)
                db.add(course)
                await db.commit()

            status_item = {
                "type": "ai_generation_status",
                "status": "completed",
                "current": total_chapters,
                "total": total_chapters,
                "message": "Tüm ders slaytları başarıyla oluşturuldu!"
            }
            curriculum = [c for c in curriculum if c.get("type") != "ai_generation_status"]
            curriculum.append(status_item)

            course.curriculum = list(curriculum)
            course.notes = list(all_notes)
            db.add(course)
            await db.commit()

        except Exception as e:
            print(f"Error in background slide generation: {e}")
            try:
                res = await db.execute(select(Course).where(Course.id == course_id))
                course = res.scalars().first()
                if course:
                    curr = list(course.curriculum or [])
                    curr = [c for c in curr if c.get("type") != "ai_generation_status"]
                    curr.append({
                        "type": "ai_generation_status",
                        "status": "failed",
                        "message": f"Slayt üretilirken hata oluştu: {str(e)}"
                    })
                    course.curriculum = curr
                    db.add(course)
                    await db.commit()
            except Exception:
                pass


@router.post("/courses/{course_id}/start_background_generation")
async def start_background_generation_api(
    course_id: int,
    req: StartBackgroundGenerationRequest,
    background_tasks: BackgroundTasks,
    teacher_id: int = Depends(get_current_teacher_id),
    db: AsyncSession = Depends(get_db)
):
    res = await db.execute(select(Course).where(Course.id == course_id, Course.teacher_id == teacher_id))
    course = res.scalars().first()
    if not course:
        raise HTTPException(status_code=404, detail="Kurs bulunamadı.")

    curriculum = list(course.curriculum or [])
    curriculum = [c for c in curriculum if c.get("type") != "ai_generation_status"]
    curriculum.append({
        "type": "ai_generation_status",
        "status": "processing",
        "current": 0,
        "total": len(req.chapters),
        "message": "Arka planda AI slayt üretimi başlatılıyor..."
    })

    course.curriculum = curriculum
    db.add(course)
    await db.commit()

    background_tasks.add_task(
        run_background_slide_generation,
        course_id=course_id,
        teacher_id=teacher_id,
        topic=req.topic,
        difficulty=req.difficulty,
        audience=req.audience,
        chapters=req.chapters,
        pdf_content=req.pdf_content
    )

    return {
        "success": True,
        "message": "Arka planda slayt üretimi başlatıldı."
    }


