services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:241120@db:5432/gomufi_db"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: my-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 241120
      POSTGRES_DB: gomufi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
