services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      # Buradaki değerler .env dosyasındakileri GEÇİCİ OLARAK (sadece bilgisayarınızda) ezer
      - FRONTEND_URL=http://localhost:5173
      - BACKEND_URL=http://localhost:8000
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
