"""sync_db_columns

Revision ID: 0bc2d2123c1c
Revises: d650a659cead
Create Date: 2026-04-18 19:25:19.223454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc2d2123c1c'
down_revision = 'd650a659cead'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
