"""add_gamification_fields

Revision ID: b86b72242cff
Revises: 0bc2d2123c1c
Create Date: 2026-05-11 14:47:00.856926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86b72242cff'
down_revision = '0bc2d2123c1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gems', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('hearts', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('streak', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'xp')
    op.drop_column('students', 'streak')
    op.drop_column('students', 'hearts')
    op.drop_column('students', 'gems')
    # ### end Alembic commands ###
