"""add_gamification_fields

Revision ID: b86b72242cff
Revises: 0bc2d2123c1c
Create Date: 2026-05-11 14:47:00.856926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86b72242cff'
down_revision = '0bc2d2123c1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE students ADD COLUMN IF NOT EXISTS gems INTEGER")
    op.execute("ALTER TABLE students ADD COLUMN IF NOT EXISTS hearts INTEGER")
    op.execute("ALTER TABLE students ADD COLUMN IF NOT EXISTS streak INTEGER")
    op.execute("ALTER TABLE students ADD COLUMN IF NOT EXISTS xp INTEGER")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'xp')
    op.drop_column('students', 'streak')
    op.drop_column('students', 'hearts')
    op.drop_column('students', 'gems')
    # ### end Alembic commands ###
