"""Initial migration and instructor notes

Revision ID: d650a659cead
Revises: 
Create Date: 2026-04-18 09:30:02.559158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd650a659cead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor_notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'instructor_notes')
    # ### end Alembic commands ###
